### ISSUE TITLE
Evaluation on Panoptic dataset. 

### ISSUE THREAD

**Issue by anl13** [zj-dong/Multi-Person-Pose-Estimation#1]
Hello. Have you evaluated your method on Panoptic dataset?  We all know that, SMPL mesh based method would result in larger MPJPE than skel point based methods like VoxelPose due to topology discrepency. However, I am curious about the SOTA quantitative performance of multiview multiple SMPL mesh recovery on Panoptic dataset. As you are the current SOTA, would you like to provide one?

**Comment by zj-dong** [comment]
Hi, thanks for your question. I estimate our method on the Panoptic dataset and find that the learning-based method like VoxelPose will have better results due to the similar training distribution between the training and test dataset (i.e. people are always standing still with fewer poses variations).  The MPJPE value of our method is larger than theirs. So we define the setting to estimate unseen poses of different people and don't choose Panoptic Studio as our test dataset. If you hope to compare with SOTA in Panoptic Studio, I think VoxelPose is still the best for their setting on multi-view multi-person pose estimation.
